#!/bin/bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

if [[ "$1" == "--dl" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/Documents &

elif [[ "$1" == "--music" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/Music &

elif [[ "$1" == "--pics" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/.config &

elif [[ "$1" == "--local" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/.local/share &

elif [[ "$1" == "--git" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/git

elif [[ "$1" == "--dev" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/dev

elif [[ "$1" == "--feup" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~/Feup

fi
