#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

if [[ "$1" == "--ff" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox-developer-edition &

elif [[ "$1" == "--dc" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--tr" ]]; then
	${EWW} close-all && rm -rf "$FILE" && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	${EWW} close-all && rm -rf "$FILE" && thunar ~ &

elif [[ "$1" == "--cd" ]]; then
	${EWW} close-all && rm -rf "$FILE" && code &

elif [[ "$1" == "--gp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && gimp &

elif [[ "$1" == "--vb" ]]; then
	${EWW} close-all && rm -rf "$FILE" && virtualbox &

elif [[ "$1" == "--sl" ]]; then
	${EWW} close-all && rm -rf "$FILE" && slack &

elif [[ "$1" == "--sp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify &

fi
